export const surpriseMePrompts: string[] = [
    'A quirky armchair in the shape of an avocado',
    'A surreal and dream-like oil painting by Salvador Dalí depicting a cat playing checkers',
    'Adorable teddy bears shopping for groceries in Japan, captured in ukiyo-e',
    'A captivating oil painting by Matisse of a humanoid robot playing chess',
    'A playful panda mad scientist mixing sparkling chemicals, in digital art form',
    "A whimsical macro 35mm photograph of two mice in Hawaii, each wearing tiny swimsuits and carrying tiny surf boards, captured in digital art",
    'A mesmerizing 3D render of a cute tropical fish in an aquarium on a dark blue background, in digital art form',
    'An astronaut relaxing in a tropical resort in space, in vaporwave style',
    'An elegant oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'A charming stained glass window depicting a hamburger and french fries',
    'A futuristic pencil and watercolor drawing of a bright city with flying cars',
    'A serene sunlit indoor lounge area with clear and translucent pastel pink pools next to a big window, captured in digital art',
    'A mystic fortune-telling shiba inu reading your fate in a giant hamburger, in digital art form',
    '"A sea otter with a pearl earring" by Johannes Vermeer, recreated in art form',
    'A vivid oil pastel drawing of an annoyed cat in a green spaceship',
    'A unique painting of a fox in the style of Starry Night',
    'A hilarious bowl of soup that looks like a monster, knitted out of multicolor wool',
    'A cute plush toy robot sitting against a yellow wall',
    'A breathtaking synthwave style sunset above the reflecting water of the sea, captured in digital art form',
    'Two futuristic towers with a skybridge covered in lush foliage, captured in digital art form',
    'A colorful 3D render of a rainbow hot air balloon flying above a reflective lake',
    'A cool comic book cover of a superhero wearing headphones',
    'A stunning explosion of colorful powder on a black background',
    'A heartwarming photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A mysterious white fur monster standing in a purple room',
    "A humorous photo of Michelangelo's sculpture of David wearing cordless headphones djing",
    'A powerful Samurai riding a horse on Mars, captured in lomography style',
    'A modern, sleek Cadillac driving along the Gardiner expressway with downtown Toronto in the background, with a lens flare, captured in 50mm photography',
    'A strikingly realistic photograph of a young woman with blue eyes and blonde hair',
    'A curious man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project, a hilarious mashup',
    'A creative velociraptor working at a hotdog stand, captured in lomography style',
    'A mysterious man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, captured in 50mm lens',
    'A living and breathing BBQ, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club with neon lights, a stunning sight',
    'The long-lost Star Wars 1990 Japanese Anime, a rare gem',
    'A delicious hamburger in the shape of a Rubik’s cube, professional food photography',
    'A stunning Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An agile astronaut encountering an alien life form on a distant planet, photography',
    'A terrifying Dinosaur exploring Cape Town, photography',
    'A old Man falling in Love with his Computer, digital art',
    'A photograph of a woman cyborg exploring Tokyo at night, lomography',
    'Dracula and Esmeralda walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave orange aeroplane stationed',
    'An acrobat wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A retro Space Shuttle flying above Cape Town, digital art',
]
